version: "3"

services:
  tor-socks-proxy:
    container_name: torproxy
    build: .
    image: sh1n3g4ter/tor-socks-proxy
    ports:
      - "127.0.0.1:8853:8853/udp"
      - "0.0.0.0:9000-9127:9000-9127/tcp"
    restart: unless-stopped
    environment:
      - TOR_CONTROL_PW=${TOR_CONTROL_PW}
      - INSTANCES_COUNT=${INSTANCES_COUNT}
